// Generated by Wrangler on Fri Jul 26 2024 11:34:40 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	REWRITE_HOSTNAME: "";
	APPEND_PATH: "";
	HANDLE_ROBOTS: false;
}
